FROM arm64v8/openjdk:17-ea-16-jdk@sha256:149f7dbd5287cb06efc8c5d0dfffeffcc36e8a9872dca7736ef8c333a3eca6a2

ARG JAR_FILE=build/libs/communityapiserver-0.0.1-SNAPSHOT.jar

COPY ${JAR_FILE} ./app.jar

ENV SPRING_PROFILES_ACTIVE dev
ENV JWT_SECRET ${JWT_SECRET}
ENV OAUTH_KAKAO_CLIENT_ID ${OAUTH_KAKAO_CLIENT_ID}
ENV OAUTH_KAKAO_CLIENT_SECRET ${OAUTH_KAKAO_CLIENT_SECRET}
ENV OAUTH_KAKAO_REDIRECT_URI ${OAUTH_KAKAO_REDIRECT_URI}
ENV OAUTH_GOOGLE_CLIENT_ID ${OAUTH_GOOGLE_CLIENT_ID}
ENV OAUTH_GOOGLE_CLIENT_SECRET ${OAUTH_GOOGLE_CLIENT_SECRET}
ENV OAUTH_GOOGLE_REDIRECT_URI ${OAUTH_GOOGLE_REDIRECT_URI}
ENV OAUTH_RIOT_CLIENT_ID ${OAUTH_RIOT_CLIENT_ID}
ENV OAUTH_RIOT_CLIENT_SECRET ${OAUTH_RIOT_CLIENT_SECRET}
ENV OAUTH_RIOT_RECIRECT_URI ${OAUTH_RIOT_RECIRECT_URI}
ENV MAIL_USERNAME ${MAIL_USERNAME}
ENV MAIL_PASSWORD ${MAIL_PASSWORD}

ENV MYSQL_HOST ${MYSQL_HOST}
ENV MYSQL_USERNAME ${MYSQL_USERNAME}
ENV MYSQL_PASSWORD ${MYSQL_PASSWORD}

ENV MONGO_HOST ${MONGO_HOST}
ENV MONGO_PORT ${MONGO_PORT}
ENV MONGO_DATABASE ${MONGO_DATABASE}
ENV MONGO_USERNAME ${MONGO_USERNAME}
ENV MONGO_PASSWORD ${MONGO_PASSWORD}
ENV MONGO_ADMIN_DB ${MONGO_ADMIN_DB}

ENV REDIS_HOST ${REDIS_HOST}
ENV REDIS_PORT ${REDIS_PORT}


ENTRYPOINT ["java", "-jar", "./app.jar"]

EXPOSE 18080